### ISSUE TITLE
PROBLEM WITH LAUNCH THE TOOL

### ISSUE THREAD

**Issue by alvarotoribioaba** [lockfale/OSINT-Framework#417]
Traceback (most recent call last):
  File "E:\Temporal\Osintgram-master\main.py", line 3, in <module>
    from src.Osintgram import Osintgram
  File "E:\Temporal\Osintgram-master\src\Osintgram.py", line 9, in <module>
    import requests
  File "C:\Users\USUARIO\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\__init__.py", line 63, in <module>
    from . import utils
  File "C:\Users\USUARIO\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\utils.py", line 27, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "C:\Users\USUARIO\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\cookies.py", line 172, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'

**Comment by biskoss12** [comment]
me too do u know how to fix it

**Comment by JamesClarke7283** [comment]
> Traceback (most recent call last): File "E:\Temporal\Osintgram-master\main.py", line 3, in from src.Osintgram import Osintgram File "E:\Temporal\Osintgram-master\src\Osintgram.py", line 9, in import requests File "C:\Users\USUARIO\AppData\Local\Programs\Python\Python310\lib\site-packages\requests__init__.py", line 63, in from . import utils File "C:\Users\USUARIO\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\utils.py", line 27, in from .cookies import RequestsCookieJar, cookiejar_from_dict File "C:\Users\USUARIO\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\cookies.py", line 172, in class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping): AttributeError: module 'collections' has no attribute 'MutableMapping'

Wrong place, this is the OSINT-Framework repository.

For Osintgram, go here instead:
https://github.com/Datalux/Osintgram


## Bug Reporting Basics
First, check you followed the install instructions correctly, if you think you did, check if there are similar open issues that already talk about the issue (more likely than not if its a crash bug, it will be a known issue not long after the regression is introduced).

I see you pasted just a stacktrace (the error output), this is a good start, but at the very bare minimum, include the following additional details (+the full stacktrace you provided).
 
**1. Program version**
**2. Full command you ran with the arguments.**

Without this, it makes it very hard for us to know what is going on (unless its a known issue, then they may close your report as duplicate and rely on the more detailed one to solve the problem).

This above approach is is the path of least resistance, while still increasing the changes of your issue solved.

Ideally (For best results):
1. Concise description of the problem
2. Full log output (usually there is a --verbose/--debug flag, search the official docs with terms like: "logging", "logs", "debug")
3. Steps to reproduce (short step 1-[n] of everything you did so they can reproduce the problem)
